version: '3.8'

services:
  frontend:
    build: .
    ports:
      # - 80:3000 # Maps port 80 on the host to port 3000 in the container
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    # Optional: If you need to set environment variables
    environment:
      # - NODE_ENV=production
      - CHOKIDAR_USEPOLLING=true

# services:
#   frontend:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       # - 80:3000 # Maps port 80 on the host to port 3000 in the container
#       - 5173:5173
#     volumes:
#       - .:/usr/src/app
#       - /usr/src/app/node_modules
#     # Optional: If you need to set environment variables
#     environment:
#       - NODE_ENV=production